"""PRAMANA AI Layer — investigative assistant and drafting aid powered by Google Gemini.

The model is given only the case records the caller passes in, which the
router has already limited to the signed-in user's authorised cases. It is
never given the synthetic dataset's answer key: its suggestions must come
from the evidence, like every other PRAMANA finding, and the officer decides.
"""
from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Any

import httpx

logger = logging.getLogger("pramana.ai")

REPO_ROOT = Path(__file__).resolve().parents[2]

# Load local .env if present
try:
    from dotenv import load_dotenv

    load_dotenv()
    if (REPO_ROOT / ".env").exists():
        load_dotenv(REPO_ROOT / ".env")
except Exception:
    pass

GEMINI_MODELS = [
    "gemini-3.5-flash-lite",
    "gemini-3.5-flash",
    "gemini-3.8-flash-lite",
    "gemini-3.8-flash",
    "gemini-3.1-flash-lite",
]

BASE_URL = "https://generativelanguage.googleapis.com/v1beta"


def get_gemini_api_key() -> str:
    key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not key:
        raise RuntimeError(
            "GEMINI_API_KEY environment variable is not configured. "
            "Please configure GEMINI_API_KEY in your .env file or Vercel project environment variables."
        )
    return key


def call_gemini(
    prompt: str,
    system_instruction: str | None = None,
    response_json: bool = False,
    temperature: float = 0.2,
    timeout_sec: float = 25.0,
) -> str:
    """Call Google Gemini API with automatic model fallback."""
    api_key = get_gemini_api_key()
    last_error: Exception | None = None

    payload: dict[str, Any] = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": temperature,
        },
    }
    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }
    if response_json:
        payload["generationConfig"]["responseMimeType"] = "application/json"

    for model in GEMINI_MODELS:
        # The key goes in a header, not the URL, so it cannot surface in
        # logged or returned error messages that quote the request URL.
        url = f"{BASE_URL}/models/{model}:generateContent"
        try:
            with httpx.Client(timeout=timeout_sec) as client:
                res = client.post(url, json=payload, headers={"x-goog-api-key": api_key})
                if res.status_code == 200:
                    data = res.json()
                    candidates = data.get("candidates", [])
                    if candidates:
                        parts = candidates[0].get("content", {}).get("parts", [])
                        if parts:
                            return parts[0].get("text", "")
                    return "No output generated by AI model."
                elif res.status_code in (404, 503, 429):
                    logger.warning("Gemini model %s returned status %d, trying fallback...", model, res.status_code)
                    last_error = RuntimeError(f"Model {model} returned status {res.status_code}")
                    continue
                else:
                    raise RuntimeError(f"Model {model} returned status {res.status_code}")
        except Exception as exc:
            logger.warning("Gemini model %s failed: %s", model, exc)
            last_error = exc
            continue

    if last_error:
        raise RuntimeError(f"All Gemini models failed. Last error: {last_error}")
    raise RuntimeError("No Gemini model responded.")


SYSTEM_PROMPT = """You are UPAKARAKA (उपकारक), the investigative assistant for PRAMANA (प्रमाण), a decision-support tool for cyber crime investigators.

In Sanskrit, Upakaraka signifies the faithful aide to the investigator in establishing proof (Pramana).

GROUNDING RULES:
1. Use only the case records supplied in the prompt. They are the only cases this officer is authorised to see.
2. Never invent names, account numbers, amounts, IFSCs, phone numbers, dates or case details. If something is not in the records, say it is not known and suggest how the officer could establish it.
3. Do not speculate about cases, people or accounts that are not in the supplied records.
4. You propose; the officer decides. Present findings as leads to verify, citing the record they come from.

FORMATTING & BEHAVIOURAL DIRECTIVES:
1. NEVER output simulated memo preambles (DO NOT write "**PRAMANA AI // ...**", "**TO:**", "**FROM:**", "**SUBJECT:**", or "**DATE:**").
2. Start directly with the findings and operational answers.
3. Be specific and cite the exact identifiers present in the records.
4. Where relevant, point the officer to statutory steps under:
   - Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS): Sec 94 (Summons to produce bank/telecom records), Sec 106 (Seizure / account debit freeze).
   - Bharatiya Nyaya Sanhita, 2023 (BNS): Sec 318(4) (Cheating), Sec 319(2) (Cheating by personation), Sec 316 (Criminal breach of trust).
   - IT Act 2000: Sec 66C, 66D, 69A.
"""


def chat_case_intelligence(
    message: str,
    case_context: dict[str, Any] | None = None,
    history: list[dict[str, str]] | None = None,
    db_extra_context: str | None = None,
) -> str:
    """Answer investigator queries with grounded, interconnected case and syndicate context."""
    active_str = ""
    if case_context:
        active_str = f"""
CURRENT ACTIVE SCREEN CONTEXT:
Case ID: {case_context.get('id', 'N/A')}
FIR No: {case_context.get('fir_no', 'N/A')} | Title: {case_context.get('title', 'N/A')}
Complainant: {case_context.get('complainant', 'N/A')} | City: {case_context.get('city', 'N/A')}
Station: {case_context.get('station', 'N/A')} | Unit: {case_context.get('unit', 'N/A')}
Status: {case_context.get('status', 'OPEN')} | Reg Date: {case_context.get('registered_on', 'N/A')}
Evidence Files: {case_context.get('evidence_count', 0)}
"""

    extra_str = db_extra_context or ""

    history_str = ""
    if history:
        for turn in history[-6:]:
            role = "Investigating Officer" if turn.get("role") in ("user", "human") else "Upakaraka"
            history_str += f"{role}: {turn.get('content', '')}\n"

    prompt = f"""
{active_str}
{extra_str}

CONVERSATION HISTORY:
{history_str}

INVESTIGATOR QUERY:
{message}

Provide a direct, fact-checked, deeply integrated forensic intelligence response.
"""
    system_instruction = SYSTEM_PROMPT
    raw_res = call_gemini(prompt, system_instruction=system_instruction, temperature=0.25)
    
    # Clean up any leftover memo headers if Gemini generated them
    clean_res = re.sub(r"^\*\*(?:PRAMANA AI|UPAKARAKA) // [^\n]+\*\*\s*", "", raw_res, flags=re.IGNORECASE)
    clean_res = re.sub(r"^\*\*TO:\*\*[^\n]+\n", "", clean_res, flags=re.IGNORECASE)
    clean_res = re.sub(r"^\*\*SUBJECT:\*\*[^\n]+\n", "", clean_res, flags=re.IGNORECASE)
    clean_res = re.sub(r"^\*\*DATE:\*\*[^\n]+\n", "", clean_res, flags=re.IGNORECASE)
    return clean_res.strip()


def analyze_case_deep(case_info: dict[str, Any]) -> dict[str, Any]:
    """Structured analysis of one case, from that case's own records only."""
    prompt = f"""
Analyse the following cyber fraud case using ONLY the records below.

CASE RECORDS (JSON):
{json.dumps(case_info, default=str, ensure_ascii=False)}

Return a JSON object with EXACTLY these keys:
{{
  "typology": "short name of the fraud typology the records indicate",
  "risk_score": <integer 0-100>,
  "confidence": "HIGH" | "MEDIUM" | "LOW" (LOW when the records are thin),
  "summary": "2-3 sentence summary citing only what the records show",
  "modus_operandi": ["step-by-step method as evidenced by the records"],
  "statutory_sections": [{{"section": "e.g. Section 318(4) BNS", "desc": "why it applies"}}],
  "syndicate_hierarchy": [{{"role": "role in the scheme", "entity": "name/identifier exactly as in the records", "details": "which record supports this"}}],
  "immediate_actions": ["concrete next investigative or statutory step"]
}}
Use empty lists where the records do not support an entry. Do not invent entities, amounts or identifiers.
"""
    raw_json = call_gemini(prompt, system_instruction=SYSTEM_PROMPT, response_json=True, temperature=0.15)
    try:
        return json.loads(raw_json)
    except Exception:
        clean = raw_json.strip().replace("```json", "").replace("```", "").strip()
        return json.loads(clean)


def draft_statutory_notice(
    notice_type: str,
    case_data: dict[str, Any],
    target_entity: dict[str, Any],
    officer: dict[str, Any],
) -> str:
    """Draft an official, court-ready statutory notice with official police formatting under BNSS/IT Act."""
    prompt = f"""
Draft an official, court-ready statutory notice under Indian Criminal Procedure laws (BNSS / IT Act).

Notice Type: {notice_type}
(Options: 'SECTION_106_BNSS' [Direct Police Debit Freeze Directive], 'SECTION_94_BNSS' [Summons to Produce Records/KYC/IPDR], 'SECTION_69A_IT_ACT' [Takedown Notice])

CASE DETAILS:
Police Station: {case_data.get('station') or '[not provided]'}
District / City: {case_data.get('city') or '[not provided]'}
FIR Number: {case_data.get('fir_no') or '[not provided]'}
Case Registered Date: {case_data.get('registered_on') or '[not provided]'}
Applicable Penal Sections: Sections 318(4), 319(2), 316 BNS, 2023 r/w Sections 66C, 66D IT Act, 2000
Complainant / Victim: {case_data.get('complainant') or '[not provided]'}

INVESTIGATING OFFICER:
Name: {officer.get('name') or '[not provided]'}
Designation: {officer.get('role_label') or '[not provided]'}
Unit: {officer.get('unit') or '[not provided]'}

TARGET RECIPIENT ENTITY:
Entity / Bank Name: {target_entity.get('name') or '[not provided]'}
Account Number / Identifier: {target_entity.get('account_no') or '[not provided]'}
Branch / IFSC: {target_entity.get('ifsc') or '[not provided]'}
Transaction / UTR Reference: {target_entity.get('utr') or '[not provided]'}
Disputed Amount to Freeze: ₹{target_entity.get('amount') or '[not provided]'}

REQUIREMENTS:
1. Departmental header: State Cyber Police Crime Branch.
2. Formal notice reference: NOTICE/CYB/2026/FIR-{case_data.get('fir_no') or 'NA'}/LEGAL-01.
3. Explicit statutory exercise of power under Section 106 BNSS (or Section 94 BNSS).
4. Direct orders: Immediate debit-freeze on the specified account, preserve CCTV/IPDR/audit logs, furnish certified Banker's Books Evidence Act certificate within 24 hours.
5. Penalty warning: Highlight Section 223 BNS for non-compliance.
6. Signature block for IO with official seal designation.
7. Where a detail above is "[not provided]", leave a clearly marked blank for the officer to fill in; do not invent it.
"""
    raw_notice = call_gemini(prompt, system_instruction=SYSTEM_PROMPT, temperature=0.15)
    return raw_notice.strip()
